- name: Create AWS tags
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo

  vars_files:
    - /root/usecases/Playbooks/credentials.txt
  roles:
    - instance_deployment

  environment:
    - AWS_ACCESS_KEY: "{{ aws_access_key }}"
    - AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"

